label: crumble.fields.category.services.label
type: structure
columns:
  name:
    width: 2/3
  id:
    width: 1/3
fields:
  name:
    label: crumble.fields.category.name.label
    type: text
    required: true
  id:
    label: crumble.fields.category.id.label
    type: slug
    translate: false
    wizard:
      field: name
      text: Generate
    required: true
    help: crumble.fields.category.id.help